/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TestStorageInterface extends ethers.utils.Interface {
  functions: {
    "get(string)": FunctionFragment;
    "set(string,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "get", values: [string]): string;
  encodeFunctionData(
    functionFragment: "set",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;

  events: {};
}

export class TestStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: TestStorageInterface;

  functions: {
    get(key: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "get(string)"(key: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    set(
      key: string,
      val: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "set(string,uint256)"(
      key: string,
      val: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  get(key: string, overrides?: CallOverrides): Promise<BigNumber>;

  "get(string)"(key: string, overrides?: CallOverrides): Promise<BigNumber>;

  set(
    key: string,
    val: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "set(string,uint256)"(
    key: string,
    val: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    get(key: string, overrides?: CallOverrides): Promise<BigNumber>;

    "get(string)"(key: string, overrides?: CallOverrides): Promise<BigNumber>;

    set(
      key: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "set(string,uint256)"(
      key: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    get(key: string, overrides?: CallOverrides): Promise<BigNumber>;

    "get(string)"(key: string, overrides?: CallOverrides): Promise<BigNumber>;

    set(
      key: string,
      val: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "set(string,uint256)"(
      key: string,
      val: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    get(key: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "get(string)"(
      key: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    set(
      key: string,
      val: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "set(string,uint256)"(
      key: string,
      val: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
